"""
serving/main.py
────────────────
VeriTune FastAPI application.

Endpoints
---------
  POST /predict              → Route ticket, run LoRA inference, apply safety filters
  GET  /health               → Liveness + readiness check
  GET  /metrics              → Prometheus metrics (text/plain) + JSON snapshot
  GET  /router/calibrate     → Trigger router re-calibration from latest val data
  POST /admin/reload-adapters → Hot-reload adapter registry from checkpoint manager
  GET  /docs                 → Swagger UI (auto-generated by FastAPI)

Startup
-------
  uvicorn serving.main:app --host 0.0.0.0 --port 8000 --workers 2

Example
-------
  curl -X POST http://localhost:8000/predict \\
    -H "Content-Type: application/json" \\
    -d '{"ticket_text": "My headphones won'\''t charge after the firmware update."}'
"""

from __future__ import annotations

import logging
import os
import time
import uuid
from contextlib import asynccontextmanager
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Request, Response, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, PlainTextResponse

from routing.models import TicketRequest, TicketResponse, Domain
from serving.monitoring import setup_structured_logging, get_metrics, RequestTrace

logger = logging.getLogger(__name__)

# ── Application state (loaded once at startup) ─────────────────────────────────

_pipeline = None      # InferencePipeline singleton


def get_pipeline():
    global _pipeline
    if _pipeline is None:
        raise HTTPException(status_code=503, detail="Inference pipeline not initialised")
    return _pipeline


# ── Lifespan (startup + shutdown) ──────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialise all resources at startup; clean up at shutdown."""
    global _pipeline
    setup_structured_logging(level=os.getenv("LOG_LEVEL", "INFO"))
    logger.info("VeriTune starting up...")

    router_path   = os.getenv("ROUTER_PATH",   "outputs/router")
    registry_path = os.getenv("REGISTRY_PATH", "outputs/checkpoints/checkpoint_registry.json")
    device        = os.getenv("DEVICE",        "cpu")

    try:
        from serving.inference import build_pipeline
        _pipeline = build_pipeline(
            router_path=router_path,
            registry_path=registry_path,
            device=device,
        )
        # Warm up adapter cache on startup to minimise first-request latency
        _pipeline.warm_up()
        logger.info("VeriTune ready ✓")
    except Exception as e:
        logger.error("Pipeline init failed: %s", e, exc_info=True)
        # Don't crash the server — /health will report not ready

    yield   # application runs

    logger.info("VeriTune shutting down")
    _pipeline = None


# ── FastAPI app ────────────────────────────────────────────────────────────────

app = FastAPI(
    title="VeriTune",
    description=(
        "Multi-domain intent router with adaptive LoRA fine-tuning for customer support. "
        "Routes tickets to domain-specialised Mistral-7B adapters. "
        "94%+ auto-resolution · <200ms p95 · $0.07/ticket."
    ),
    version="1.0.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# ── Request ID middleware ──────────────────────────────────────────────────────

@app.middleware("http")
async def add_request_id(request: Request, call_next):
    """Attach X-Request-ID to every request/response for tracing."""
    request_id = request.headers.get("X-Request-ID", str(uuid.uuid4())[:8])
    response   = await call_next(request)
    response.headers["X-Request-ID"] = request_id
    return response


# ── /predict ───────────────────────────────────────────────────────────────────

@app.post(
    "/predict",
    response_model=TicketResponse,
    summary="Route and resolve a support ticket",
    tags=["inference"],
    responses={
        200: {"description": "Successful routing and response generation"},
        422: {"description": "Validation error in request body"},
        503: {"description": "Pipeline not ready"},
    },
)
async def predict(request: TicketRequest) -> TicketResponse:
    """
    Route a customer support ticket to the appropriate domain LoRA adapter
    and generate a response.

    The pipeline:
    1. SBERT intent router classifies the ticket (~12ms)
    2. LoRA selector picks the domain adapter (with escalation safety override)
    3. LRU cache serves adapter weights (~8ms hit / ~500ms miss)
    4. Mistral-7B generates a response (~105ms)
    5. Safety filters check for escalation, PII, hallucinations, tone (~5ms)

    Returns a TicketResponse with the generated response, routing metadata,
    and per-stage latency breakdown.
    """
    pipeline = get_pipeline()
    try:
        return pipeline.predict(request)
    except Exception as e:
        logger.error("Prediction error: %s", e, exc_info=True)
        raise HTTPException(status_code=500, detail=f"Inference error: {str(e)}")


# ── /predict/batch ─────────────────────────────────────────────────────────────

@app.post(
    "/predict/batch",
    response_model=List[TicketResponse],
    summary="Batch predict (up to 32 tickets)",
    tags=["inference"],
)
async def predict_batch(requests: List[TicketRequest]) -> List[TicketResponse]:
    """
    Process a batch of tickets. Max 32 tickets per request.
    Each ticket is processed sequentially through the full pipeline.
    """
    if len(requests) > 32:
        raise HTTPException(
            status_code=422,
            detail=f"Batch size {len(requests)} exceeds maximum of 32",
        )
    pipeline = get_pipeline()
    try:
        return pipeline.predict_batch(requests)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ── /health ────────────────────────────────────────────────────────────────────

@app.get(
    "/health",
    summary="Liveness and readiness check",
    tags=["ops"],
    responses={
        200: {"description": "Service healthy and ready"},
        503: {"description": "Service not ready"},
    },
)
async def health():
    """
    Returns component health status.

    - `status: "ok"` → all components loaded, ready to serve
    - `status: "degraded"` → serving but with warnings
    - `status: "not_ready"` → pipeline not initialised
    """
    global _pipeline
    if _pipeline is None:
        return JSONResponse(
            status_code=503,
            content={
                "status": "not_ready",
                "message": "Inference pipeline not initialised",
                "timestamp": time.time(),
            },
        )

    health_data = _pipeline.health_check()
    status_code = 200 if health_data.get("status") == "ok" else 503
    health_data["timestamp"] = time.time()
    return JSONResponse(status_code=status_code, content=health_data)


# ── /metrics ───────────────────────────────────────────────────────────────────

@app.get(
    "/metrics",
    summary="Prometheus metrics + JSON snapshot",
    tags=["ops"],
)
async def metrics(format: str = "json"):
    """
    Return observability metrics.

    - `?format=json`  (default) → JSON snapshot of key business metrics
    - `?format=prometheus` → Prometheus text format for scraping
    """
    metrics_obj = get_metrics()

    if format == "prometheus":
        try:
            from prometheus_client import generate_latest, CONTENT_TYPE_LATEST
            return Response(
                content=generate_latest(),
                media_type=CONTENT_TYPE_LATEST,
            )
        except ImportError:
            pass  # fall through to JSON

    snapshot = metrics_obj.snapshot()
    snapshot["timestamp"] = time.time()
    return JSONResponse(content=snapshot)


# ── /router/calibrate ─────────────────────────────────────────────────────────

@app.post(
    "/router/calibrate",
    summary="Re-calibrate router temperature on validation data",
    tags=["ops"],
)
async def calibrate_router(
    background_tasks: BackgroundTasks,
    domain: Optional[str] = None,
    val_samples: int = 200,
):
    """
    Trigger router temperature calibration in the background.

    Loads validation examples from the processed data directory,
    runs a temperature grid search to minimise ECE, and saves the
    updated router state to disk.

    Returns immediately with a job_id; calibration runs in background.
    """
    job_id = str(uuid.uuid4())[:8]

    def _calibrate():
        pipeline = _pipeline
        if pipeline is None or not pipeline._check_router():
            logger.warning("Calibration skipped — router not fitted")
            return

        try:
            from data.loaders import load_all_domains
            from routing.models import Domain as D

            domain_splits = load_all_domains(
                processed_dir="data/datasets/processed"
            )
            domains_to_calibrate = [domain] if domain else list(domain_splits.keys())

            for dom in domains_to_calibrate:
                if dom not in domain_splits:
                    continue
                val_ds = domain_splits[dom].get("val", domain_splits[dom].get("test"))
                if val_ds is None:
                    continue
                val_texts  = val_ds["text"][:val_samples]
                val_labels = [D(dom)] * len(val_texts)
                result = pipeline.router.calibrate(val_texts, val_labels)
                logger.info(
                    "Calibration [%s] job=%s ECE=%.4f accuracy=%.3f",
                    dom, job_id, result.ece, result.accuracy,
                )

            pipeline.router.save("outputs/router")
            logger.info("Router saved after calibration (job=%s)", job_id)

        except Exception as e:
            logger.error("Calibration job %s failed: %s", job_id, e, exc_info=True)

    background_tasks.add_task(_calibrate)
    return {"job_id": job_id, "status": "started", "message": "Calibration running in background"}


# ── /admin/reload-adapters ────────────────────────────────────────────────────

@app.post(
    "/admin/reload-adapters",
    summary="Hot-reload adapter registry from latest checkpoints",
    tags=["ops"],
)
async def reload_adapters():
    """
    Reload the adapter registry from the checkpoint registry on disk.
    Clears the LRU cache so new adapters are picked up on next request.

    Use after promoting new best checkpoints with scripts/train_domain_loras.py.
    """
    global _pipeline
    if _pipeline is None:
        raise HTTPException(status_code=503, detail="Pipeline not ready")

    try:
        from training.checkpoint_manager import CheckpointManager
        from routing.lora_selector import AdapterRegistry

        registry_path = os.getenv(
            "REGISTRY_PATH", "outputs/checkpoints/checkpoint_registry.json"
        )
        manager = CheckpointManager()
        manager.load_registry(registry_path)
        new_registry = AdapterRegistry.from_checkpoint_manager(manager)
        _pipeline.selector.update_adapter_registry(new_registry)
        _pipeline.loader.clear_cache()
        logger.info("Adapter registry reloaded")
        return {
            "status":  "ok",
            "message": "Adapter registry reloaded and cache cleared",
            "domains": list(new_registry.paths.keys()),
        }
    except Exception as e:
        logger.error("Reload failed: %s", e)
        raise HTTPException(status_code=500, detail=str(e))


# ── /info ──────────────────────────────────────────────────────────────────────

@app.get(
    "/info",
    summary="Service version and configuration info",
    tags=["ops"],
)
async def info():
    """Return service version, model info, and configuration."""
    return {
        "service":      "VeriTune",
        "version":      "1.0.0",
        "base_model":   "mistralai/Mistral-7B-Instruct-v0.2",
        "router_model": "all-MiniLM-L6-v2",
        "domains":      ["technical", "billing", "returns", "escalation"],
        "lora_ranks":   {"technical": 32, "billing": 24, "returns": 28, "escalation": 8},
        "targets": {
            "auto_resolution_rate": ">94%",
            "escalation_fnr":       "<0.5%",
            "latency_p95_ms":       "<200",
            "cost_per_ticket":      "$0.07",
        },
        "pipeline_ready": _pipeline is not None,
    }
